### ISSUE TITLE
Stellar core config history domain missing `{0}`

### ISSUE THREAD

**Issue by jayz22** [stellarbeat/js-stellar-domain#15]
The "Stellar Core Config" displayed in stellarbeats.io missing `{0}`. For example [SDF 1](https://stellarbeat.io/nodes/GCGB2S2KGYARPVIA37HYZXVRM2YZUEXA6S33ZU5BUDC6THSB62LZSTYH?center=1&no-scroll=1&network=public), click on "Stellar Core Config", shows `HISTORY = "curl -sf http://history.stellar.org/prd/core-live/core_live_001/ -o {1}"`. (`{0}` missing at the end of "core_live_001/")
Presumably this [line ](https://github.com/stellarbeat/js-stellar-domain/blob/9808ba3cf3ee2cf6cea848a0bc8ebff0c872baf7/src/stellar-core-configuration-generator.ts#L93) needs to change.

**Comment by pieterjan84** [comment]
Fixed, thanks!
